export const THEMES = [
    { id: 'animals',        label: 'Animals' },
    { id: 'countries',      label: 'Countries' },
    { id: 'cities',         label: 'Cities' },
    { id: 'fruit',          label: 'Fruit' },
    { id: 'vegetables',     label: 'Vegetables' },
    { id: 'sports',         label: 'Sports' },
    { id: 'instruments',    label: 'Musical Instruments' },
    { id: 'planets',        label: 'Planets & Moons' },
    { id: 'professions',    label: 'Professions' },
    { id: 'drinks',         label: 'Drinks' },
    { id: 'summer',         label: 'Summer' },
    { id: 'vehicles',       label: 'Vehicles' },
    { id: 'colors',         label: 'Colors' },
    { id: 'buildings',      label: 'Buildings' },
    { id: 'insects',        label: 'Insects' },
];